// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module simulatedAnnealingTop_exec_pipeline (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        n2c_address0,
        n2c_ce0,
        n2c_we0,
        n2c_d0,
        n2c_q0,
        n2c_address1,
        n2c_ce1,
        n2c_q1,
        c2n_address0,
        c2n_ce0,
        c2n_we0,
        c2n_d0,
        c2n_q0,
        c2n_address1,
        c2n_ce1,
        c2n_q1,
        n_address0,
        n_ce0,
        n_q0,
        n_address1,
        n_ce1,
        n_q1
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] n2c_address0;
output   n2c_ce0;
output  [99:0] n2c_we0;
output  [799:0] n2c_d0;
input  [799:0] n2c_q0;
output  [2:0] n2c_address1;
output   n2c_ce1;
input  [799:0] n2c_q1;
output  [2:0] c2n_address0;
output   c2n_ce0;
output  [99:0] c2n_we0;
output  [799:0] c2n_d0;
input  [799:0] c2n_q0;
output  [2:0] c2n_address1;
output   c2n_ce1;
input  [799:0] c2n_q1;
output  [6:0] n_address0;
output   n_ce0;
input  [31:0] n_q0;
output  [6:0] n_address1;
output   n_ce1;
input  [31:0] n_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [2:0] st0_m_cell_a_V_address0;
reg    st0_m_cell_a_V_ce0;
reg    st0_m_cell_a_V_we0;
reg   [7:0] st0_m_cell_a_V_d0;
wire   [7:0] st0_m_cell_a_V_q0;
reg   [2:0] st0_m_cell_a_V_address1;
reg    st0_m_cell_a_V_ce1;
reg    st0_m_cell_a_V_we1;
reg   [2:0] st0_m_cell_b_V_address0;
reg    st0_m_cell_b_V_ce0;
reg    st0_m_cell_b_V_we0;
reg   [7:0] st0_m_cell_b_V_d0;
wire   [7:0] st0_m_cell_b_V_q0;
reg   [2:0] st0_m_th_valid_address0;
reg    st0_m_th_valid_ce0;
reg    st0_m_th_valid_we0;
reg   [0:0] st0_m_th_valid_d0;
wire   [0:0] st0_m_th_valid_q0;
reg   [3:0] st1_m_fifo_a_m_arr_th_idx_V_address0;
reg    st1_m_fifo_a_m_arr_th_idx_V_ce0;
reg    st1_m_fifo_a_m_arr_th_idx_V_we0;
reg   [7:0] st1_m_fifo_a_m_arr_th_idx_V_d0;
wire   [7:0] st1_m_fifo_a_m_arr_th_idx_V_q0;
reg   [3:0] st1_m_fifo_a_m_arr_cell_V_address0;
reg    st1_m_fifo_a_m_arr_cell_V_ce0;
reg    st1_m_fifo_a_m_arr_cell_V_we0;
reg   [7:0] st1_m_fifo_a_m_arr_cell_V_d0;
wire   [7:0] st1_m_fifo_a_m_arr_cell_V_q0;
reg   [3:0] st1_m_fifo_a_m_arr_node_V_address0;
reg    st1_m_fifo_a_m_arr_node_V_ce0;
reg    st1_m_fifo_a_m_arr_node_V_we0;
reg   [7:0] st1_m_fifo_a_m_arr_node_V_d0;
wire   [7:0] st1_m_fifo_a_m_arr_node_V_q0;
reg   [3:0] st1_m_fifo_b_m_arr_th_idx_V_address0;
reg    st1_m_fifo_b_m_arr_th_idx_V_ce0;
reg    st1_m_fifo_b_m_arr_th_idx_V_we0;
reg   [7:0] st1_m_fifo_b_m_arr_th_idx_V_d0;
wire   [7:0] st1_m_fifo_b_m_arr_th_idx_V_q0;
reg   [3:0] st1_m_fifo_b_m_arr_cell_V_address0;
reg    st1_m_fifo_b_m_arr_cell_V_ce0;
reg    st1_m_fifo_b_m_arr_cell_V_we0;
reg   [7:0] st1_m_fifo_b_m_arr_cell_V_d0;
wire   [7:0] st1_m_fifo_b_m_arr_cell_V_q0;
reg   [3:0] st1_m_fifo_b_m_arr_node_V_address0;
reg    st1_m_fifo_b_m_arr_node_V_ce0;
reg    st1_m_fifo_b_m_arr_node_V_we0;
reg   [7:0] st1_m_fifo_b_m_arr_node_V_d0;
wire   [7:0] st1_m_fifo_b_m_arr_node_V_q0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_start;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_done;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_idle;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_ready;
wire   [3:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_th_idx_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_th_idx_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_th_idx_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_th_idx_V_d0;
wire   [3:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_cell_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_cell_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_cell_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_cell_V_d0;
wire   [3:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_node_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_node_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_node_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_node_V_d0;
wire   [3:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_th_idx_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_th_idx_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_th_idx_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_th_idx_V_d0;
wire   [3:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_cell_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_cell_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_cell_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_cell_V_d0;
wire   [3:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_node_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_node_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_node_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_node_V_d0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_size_V_out;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_size_V_out_ap_vld;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_rear_V_7_out;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_rear_V_7_out_ap_vld;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_size_V_out;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_size_V_out_ap_vld;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_rear_V_7_out;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_rear_V_7_out_ap_vld;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_start;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_done;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_idle;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_ready;
wire   [2:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_ce0;
wire   [99:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_we0;
wire   [799:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_d0;
wire   [2:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_address1;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_ce1;
wire   [2:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_ce0;
wire   [99:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_we0;
wire   [799:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_d0;
wire   [2:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_address1;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_ce1;
wire   [6:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n_ce0;
wire   [6:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n_address1;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n_ce1;
wire   [2:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_th_valid_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_th_valid_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_th_valid_we0;
wire   [0:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_th_valid_d0;
wire   [2:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_a_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_a_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_a_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_a_V_d0;
wire   [2:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_b_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_b_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_b_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_b_V_d0;
wire   [3:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_th_idx_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_th_idx_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_th_idx_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_th_idx_V_d0;
wire   [3:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_cell_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_cell_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_cell_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_cell_V_d0;
wire   [3:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_node_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_node_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_node_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_node_V_d0;
wire   [3:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_th_idx_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_th_idx_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_th_idx_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_th_idx_V_d0;
wire   [3:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_cell_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_cell_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_cell_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_cell_V_d0;
wire   [3:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_node_V_address0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_node_V_ce0;
wire    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_node_V_we0;
wire   [7:0] grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_node_V_d0;
reg    grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_start_reg = 1'b0;
#0 grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_start_reg = 1'b0;
end

simulatedAnnealingTop_exec_pipeline_st0_m_cell_a_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
st0_m_cell_a_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(st0_m_cell_a_V_address0),
    .ce0(st0_m_cell_a_V_ce0),
    .we0(st0_m_cell_a_V_we0),
    .d0(st0_m_cell_a_V_d0),
    .q0(st0_m_cell_a_V_q0),
    .address1(st0_m_cell_a_V_address1),
    .ce1(st0_m_cell_a_V_ce1),
    .we1(st0_m_cell_a_V_we1),
    .d1(8'd0)
);

simulatedAnnealingTop_exec_pipeline_st0_m_cell_b_V_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
st0_m_cell_b_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(st0_m_cell_b_V_address0),
    .ce0(st0_m_cell_b_V_ce0),
    .we0(st0_m_cell_b_V_we0),
    .d0(st0_m_cell_b_V_d0),
    .q0(st0_m_cell_b_V_q0)
);

simulatedAnnealingTop_exec_pipeline_st0_m_th_valid_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 6 ),
    .AddressWidth( 3 ))
st0_m_th_valid_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(st0_m_th_valid_address0),
    .ce0(st0_m_th_valid_ce0),
    .we0(st0_m_th_valid_we0),
    .d0(st0_m_th_valid_d0),
    .q0(st0_m_th_valid_q0)
);

simulatedAnnealingTop_exec_pipeline_st1_m_fifo_a_m_arr_th_idx_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
st1_m_fifo_a_m_arr_th_idx_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(st1_m_fifo_a_m_arr_th_idx_V_address0),
    .ce0(st1_m_fifo_a_m_arr_th_idx_V_ce0),
    .we0(st1_m_fifo_a_m_arr_th_idx_V_we0),
    .d0(st1_m_fifo_a_m_arr_th_idx_V_d0),
    .q0(st1_m_fifo_a_m_arr_th_idx_V_q0)
);

simulatedAnnealingTop_exec_pipeline_st1_m_fifo_a_m_arr_th_idx_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
st1_m_fifo_a_m_arr_cell_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(st1_m_fifo_a_m_arr_cell_V_address0),
    .ce0(st1_m_fifo_a_m_arr_cell_V_ce0),
    .we0(st1_m_fifo_a_m_arr_cell_V_we0),
    .d0(st1_m_fifo_a_m_arr_cell_V_d0),
    .q0(st1_m_fifo_a_m_arr_cell_V_q0)
);

simulatedAnnealingTop_exec_pipeline_st1_m_fifo_a_m_arr_th_idx_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
st1_m_fifo_a_m_arr_node_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(st1_m_fifo_a_m_arr_node_V_address0),
    .ce0(st1_m_fifo_a_m_arr_node_V_ce0),
    .we0(st1_m_fifo_a_m_arr_node_V_we0),
    .d0(st1_m_fifo_a_m_arr_node_V_d0),
    .q0(st1_m_fifo_a_m_arr_node_V_q0)
);

simulatedAnnealingTop_exec_pipeline_st1_m_fifo_a_m_arr_th_idx_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
st1_m_fifo_b_m_arr_th_idx_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(st1_m_fifo_b_m_arr_th_idx_V_address0),
    .ce0(st1_m_fifo_b_m_arr_th_idx_V_ce0),
    .we0(st1_m_fifo_b_m_arr_th_idx_V_we0),
    .d0(st1_m_fifo_b_m_arr_th_idx_V_d0),
    .q0(st1_m_fifo_b_m_arr_th_idx_V_q0)
);

simulatedAnnealingTop_exec_pipeline_st1_m_fifo_a_m_arr_th_idx_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
st1_m_fifo_b_m_arr_cell_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(st1_m_fifo_b_m_arr_cell_V_address0),
    .ce0(st1_m_fifo_b_m_arr_cell_V_ce0),
    .we0(st1_m_fifo_b_m_arr_cell_V_we0),
    .d0(st1_m_fifo_b_m_arr_cell_V_d0),
    .q0(st1_m_fifo_b_m_arr_cell_V_q0)
);

simulatedAnnealingTop_exec_pipeline_st1_m_fifo_a_m_arr_th_idx_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
st1_m_fifo_b_m_arr_node_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(st1_m_fifo_b_m_arr_node_V_address0),
    .ce0(st1_m_fifo_b_m_arr_node_V_ce0),
    .we0(st1_m_fifo_b_m_arr_node_V_we0),
    .d0(st1_m_fifo_b_m_arr_node_V_d0),
    .q0(st1_m_fifo_b_m_arr_node_V_q0)
);

simulatedAnnealingTop_exec_pipeline_Pipeline_VITIS_LOOP_6_1 grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_start),
    .ap_done(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_done),
    .ap_idle(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_idle),
    .ap_ready(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_ready),
    .st1_m_fifo_a_m_arr_th_idx_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_th_idx_V_address0),
    .st1_m_fifo_a_m_arr_th_idx_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_th_idx_V_ce0),
    .st1_m_fifo_a_m_arr_th_idx_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_th_idx_V_we0),
    .st1_m_fifo_a_m_arr_th_idx_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_th_idx_V_d0),
    .st1_m_fifo_a_m_arr_cell_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_cell_V_address0),
    .st1_m_fifo_a_m_arr_cell_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_cell_V_ce0),
    .st1_m_fifo_a_m_arr_cell_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_cell_V_we0),
    .st1_m_fifo_a_m_arr_cell_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_cell_V_d0),
    .st1_m_fifo_a_m_arr_node_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_node_V_address0),
    .st1_m_fifo_a_m_arr_node_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_node_V_ce0),
    .st1_m_fifo_a_m_arr_node_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_node_V_we0),
    .st1_m_fifo_a_m_arr_node_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_node_V_d0),
    .st1_m_fifo_b_m_arr_th_idx_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_th_idx_V_address0),
    .st1_m_fifo_b_m_arr_th_idx_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_th_idx_V_ce0),
    .st1_m_fifo_b_m_arr_th_idx_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_th_idx_V_we0),
    .st1_m_fifo_b_m_arr_th_idx_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_th_idx_V_d0),
    .st1_m_fifo_b_m_arr_cell_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_cell_V_address0),
    .st1_m_fifo_b_m_arr_cell_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_cell_V_ce0),
    .st1_m_fifo_b_m_arr_cell_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_cell_V_we0),
    .st1_m_fifo_b_m_arr_cell_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_cell_V_d0),
    .st1_m_fifo_b_m_arr_node_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_node_V_address0),
    .st1_m_fifo_b_m_arr_node_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_node_V_ce0),
    .st1_m_fifo_b_m_arr_node_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_node_V_we0),
    .st1_m_fifo_b_m_arr_node_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_node_V_d0),
    .st1_m_fifo_a_m_size_V_out(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_size_V_out),
    .st1_m_fifo_a_m_size_V_out_ap_vld(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_size_V_out_ap_vld),
    .st1_m_fifo_a_m_rear_V_7_out(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_rear_V_7_out),
    .st1_m_fifo_a_m_rear_V_7_out_ap_vld(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_rear_V_7_out_ap_vld),
    .st1_m_fifo_b_m_size_V_out(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_size_V_out),
    .st1_m_fifo_b_m_size_V_out_ap_vld(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_size_V_out_ap_vld),
    .st1_m_fifo_b_m_rear_V_7_out(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_rear_V_7_out),
    .st1_m_fifo_b_m_rear_V_7_out_ap_vld(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_rear_V_7_out_ap_vld)
);

simulatedAnnealingTop_exec_pipeline_Pipeline_VITIS_LOOP_27_1 grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_start),
    .ap_done(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_done),
    .ap_idle(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_idle),
    .ap_ready(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_ready),
    .st1_m_fifo_a_m_size_V_reload(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_size_V_out),
    .st1_m_fifo_a_m_rear_V_7_reload(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_rear_V_7_out),
    .st1_m_fifo_b_m_size_V_reload(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_size_V_out),
    .st1_m_fifo_b_m_rear_V_7_reload(grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_rear_V_7_out),
    .n2c_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_address0),
    .n2c_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_ce0),
    .n2c_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_we0),
    .n2c_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_d0),
    .n2c_q0(n2c_q0),
    .n2c_address1(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_address1),
    .n2c_ce1(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_ce1),
    .n2c_q1(n2c_q1),
    .c2n_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_address0),
    .c2n_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_ce0),
    .c2n_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_we0),
    .c2n_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_d0),
    .c2n_q0(c2n_q0),
    .c2n_address1(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_address1),
    .c2n_ce1(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_ce1),
    .c2n_q1(c2n_q1),
    .n_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n_address0),
    .n_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n_ce0),
    .n_q0(n_q0),
    .n_address1(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n_address1),
    .n_ce1(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n_ce1),
    .n_q1(n_q1),
    .st0_m_th_valid_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_th_valid_address0),
    .st0_m_th_valid_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_th_valid_ce0),
    .st0_m_th_valid_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_th_valid_we0),
    .st0_m_th_valid_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_th_valid_d0),
    .st0_m_th_valid_q0(st0_m_th_valid_q0),
    .st0_m_cell_a_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_a_V_address0),
    .st0_m_cell_a_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_a_V_ce0),
    .st0_m_cell_a_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_a_V_we0),
    .st0_m_cell_a_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_a_V_d0),
    .st0_m_cell_a_V_q0(st0_m_cell_a_V_q0),
    .st0_m_cell_b_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_b_V_address0),
    .st0_m_cell_b_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_b_V_ce0),
    .st0_m_cell_b_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_b_V_we0),
    .st0_m_cell_b_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_b_V_d0),
    .st0_m_cell_b_V_q0(st0_m_cell_b_V_q0),
    .st1_m_fifo_a_m_arr_th_idx_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_th_idx_V_address0),
    .st1_m_fifo_a_m_arr_th_idx_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_th_idx_V_ce0),
    .st1_m_fifo_a_m_arr_th_idx_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_th_idx_V_we0),
    .st1_m_fifo_a_m_arr_th_idx_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_th_idx_V_d0),
    .st1_m_fifo_a_m_arr_th_idx_V_q0(st1_m_fifo_a_m_arr_th_idx_V_q0),
    .st1_m_fifo_a_m_arr_cell_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_cell_V_address0),
    .st1_m_fifo_a_m_arr_cell_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_cell_V_ce0),
    .st1_m_fifo_a_m_arr_cell_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_cell_V_we0),
    .st1_m_fifo_a_m_arr_cell_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_cell_V_d0),
    .st1_m_fifo_a_m_arr_cell_V_q0(st1_m_fifo_a_m_arr_cell_V_q0),
    .st1_m_fifo_a_m_arr_node_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_node_V_address0),
    .st1_m_fifo_a_m_arr_node_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_node_V_ce0),
    .st1_m_fifo_a_m_arr_node_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_node_V_we0),
    .st1_m_fifo_a_m_arr_node_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_node_V_d0),
    .st1_m_fifo_a_m_arr_node_V_q0(st1_m_fifo_a_m_arr_node_V_q0),
    .st1_m_fifo_b_m_arr_th_idx_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_th_idx_V_address0),
    .st1_m_fifo_b_m_arr_th_idx_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_th_idx_V_ce0),
    .st1_m_fifo_b_m_arr_th_idx_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_th_idx_V_we0),
    .st1_m_fifo_b_m_arr_th_idx_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_th_idx_V_d0),
    .st1_m_fifo_b_m_arr_th_idx_V_q0(st1_m_fifo_b_m_arr_th_idx_V_q0),
    .st1_m_fifo_b_m_arr_cell_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_cell_V_address0),
    .st1_m_fifo_b_m_arr_cell_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_cell_V_ce0),
    .st1_m_fifo_b_m_arr_cell_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_cell_V_we0),
    .st1_m_fifo_b_m_arr_cell_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_cell_V_d0),
    .st1_m_fifo_b_m_arr_cell_V_q0(st1_m_fifo_b_m_arr_cell_V_q0),
    .st1_m_fifo_b_m_arr_node_V_address0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_node_V_address0),
    .st1_m_fifo_b_m_arr_node_V_ce0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_node_V_ce0),
    .st1_m_fifo_b_m_arr_node_V_we0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_node_V_we0),
    .st1_m_fifo_b_m_arr_node_V_d0(grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_node_V_d0),
    .st1_m_fifo_b_m_arr_node_V_q0(st1_m_fifo_b_m_arr_node_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_start_reg <= 1'b1;
        end else if ((grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_ready == 1'b1)) begin
            grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_start_reg <= 1'b1;
        end else if ((grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_ready == 1'b1)) begin
            grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        st0_m_cell_a_V_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        st0_m_cell_a_V_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        st0_m_cell_a_V_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        st0_m_cell_a_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_a_V_address0;
    end else begin
        st0_m_cell_a_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        st0_m_cell_a_V_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        st0_m_cell_a_V_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        st0_m_cell_a_V_address1 = 64'd0;
    end else begin
        st0_m_cell_a_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_done == 1'b1)))) begin
        st0_m_cell_a_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        st0_m_cell_a_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_a_V_ce0;
    end else begin
        st0_m_cell_a_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_done == 1'b1)))) begin
        st0_m_cell_a_V_ce1 = 1'b1;
    end else begin
        st0_m_cell_a_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        st0_m_cell_a_V_d0 = 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        st0_m_cell_a_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_a_V_d0;
    end else begin
        st0_m_cell_a_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_done == 1'b1)))) begin
        st0_m_cell_a_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        st0_m_cell_a_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_a_V_we0;
    end else begin
        st0_m_cell_a_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_done == 1'b1)))) begin
        st0_m_cell_a_V_we1 = 1'b1;
    end else begin
        st0_m_cell_a_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        st0_m_cell_b_V_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        st0_m_cell_b_V_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        st0_m_cell_b_V_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        st0_m_cell_b_V_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        st0_m_cell_b_V_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        st0_m_cell_b_V_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        st0_m_cell_b_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_b_V_address0;
    end else begin
        st0_m_cell_b_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        st0_m_cell_b_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        st0_m_cell_b_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_b_V_ce0;
    end else begin
        st0_m_cell_b_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state1))) begin
        st0_m_cell_b_V_d0 = 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        st0_m_cell_b_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_b_V_d0;
    end else begin
        st0_m_cell_b_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        st0_m_cell_b_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        st0_m_cell_b_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_cell_b_V_we0;
    end else begin
        st0_m_cell_b_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        st0_m_th_valid_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        st0_m_th_valid_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        st0_m_th_valid_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        st0_m_th_valid_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        st0_m_th_valid_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        st0_m_th_valid_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        st0_m_th_valid_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_th_valid_address0;
    end else begin
        st0_m_th_valid_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        st0_m_th_valid_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        st0_m_th_valid_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_th_valid_ce0;
    end else begin
        st0_m_th_valid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state1))) begin
        st0_m_th_valid_d0 = 1'd1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        st0_m_th_valid_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_th_valid_d0;
    end else begin
        st0_m_th_valid_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        st0_m_th_valid_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        st0_m_th_valid_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st0_m_th_valid_we0;
    end else begin
        st0_m_th_valid_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_a_m_arr_cell_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_cell_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_a_m_arr_cell_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_cell_V_address0;
    end else begin
        st1_m_fifo_a_m_arr_cell_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_a_m_arr_cell_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_cell_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_a_m_arr_cell_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_cell_V_ce0;
    end else begin
        st1_m_fifo_a_m_arr_cell_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_a_m_arr_cell_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_cell_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_a_m_arr_cell_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_cell_V_d0;
    end else begin
        st1_m_fifo_a_m_arr_cell_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_a_m_arr_cell_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_cell_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_a_m_arr_cell_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_cell_V_we0;
    end else begin
        st1_m_fifo_a_m_arr_cell_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_a_m_arr_node_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_node_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_a_m_arr_node_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_node_V_address0;
    end else begin
        st1_m_fifo_a_m_arr_node_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_a_m_arr_node_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_node_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_a_m_arr_node_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_node_V_ce0;
    end else begin
        st1_m_fifo_a_m_arr_node_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_a_m_arr_node_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_node_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_a_m_arr_node_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_node_V_d0;
    end else begin
        st1_m_fifo_a_m_arr_node_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_a_m_arr_node_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_node_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_a_m_arr_node_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_node_V_we0;
    end else begin
        st1_m_fifo_a_m_arr_node_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_a_m_arr_th_idx_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_th_idx_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_a_m_arr_th_idx_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_th_idx_V_address0;
    end else begin
        st1_m_fifo_a_m_arr_th_idx_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_a_m_arr_th_idx_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_th_idx_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_a_m_arr_th_idx_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_th_idx_V_ce0;
    end else begin
        st1_m_fifo_a_m_arr_th_idx_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_a_m_arr_th_idx_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_th_idx_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_a_m_arr_th_idx_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_th_idx_V_d0;
    end else begin
        st1_m_fifo_a_m_arr_th_idx_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_a_m_arr_th_idx_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_a_m_arr_th_idx_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_a_m_arr_th_idx_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_a_m_arr_th_idx_V_we0;
    end else begin
        st1_m_fifo_a_m_arr_th_idx_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_b_m_arr_cell_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_cell_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_b_m_arr_cell_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_cell_V_address0;
    end else begin
        st1_m_fifo_b_m_arr_cell_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_b_m_arr_cell_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_cell_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_b_m_arr_cell_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_cell_V_ce0;
    end else begin
        st1_m_fifo_b_m_arr_cell_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_b_m_arr_cell_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_cell_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_b_m_arr_cell_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_cell_V_d0;
    end else begin
        st1_m_fifo_b_m_arr_cell_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_b_m_arr_cell_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_cell_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_b_m_arr_cell_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_cell_V_we0;
    end else begin
        st1_m_fifo_b_m_arr_cell_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_b_m_arr_node_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_node_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_b_m_arr_node_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_node_V_address0;
    end else begin
        st1_m_fifo_b_m_arr_node_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_b_m_arr_node_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_node_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_b_m_arr_node_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_node_V_ce0;
    end else begin
        st1_m_fifo_b_m_arr_node_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_b_m_arr_node_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_node_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_b_m_arr_node_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_node_V_d0;
    end else begin
        st1_m_fifo_b_m_arr_node_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_b_m_arr_node_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_node_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_b_m_arr_node_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_node_V_we0;
    end else begin
        st1_m_fifo_b_m_arr_node_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_b_m_arr_th_idx_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_th_idx_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_b_m_arr_th_idx_V_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_th_idx_V_address0;
    end else begin
        st1_m_fifo_b_m_arr_th_idx_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_b_m_arr_th_idx_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_th_idx_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_b_m_arr_th_idx_V_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_th_idx_V_ce0;
    end else begin
        st1_m_fifo_b_m_arr_th_idx_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_b_m_arr_th_idx_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_th_idx_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_b_m_arr_th_idx_V_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_th_idx_V_d0;
    end else begin
        st1_m_fifo_b_m_arr_th_idx_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        st1_m_fifo_b_m_arr_th_idx_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_st1_m_fifo_b_m_arr_th_idx_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        st1_m_fifo_b_m_arr_th_idx_V_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_st1_m_fifo_b_m_arr_th_idx_V_we0;
    end else begin
        st1_m_fifo_b_m_arr_th_idx_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign c2n_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_address0;

assign c2n_address1 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_address1;

assign c2n_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_ce0;

assign c2n_ce1 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_ce1;

assign c2n_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_d0;

assign c2n_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_c2n_we0;

assign grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_start = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_ap_start_reg;

assign grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_start = grp_exec_pipeline_Pipeline_VITIS_LOOP_6_1_fu_253_ap_start_reg;

assign n2c_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_address0;

assign n2c_address1 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_address1;

assign n2c_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_ce0;

assign n2c_ce1 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_ce1;

assign n2c_d0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_d0;

assign n2c_we0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n2c_we0;

assign n_address0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n_address0;

assign n_address1 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n_address1;

assign n_ce0 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n_ce0;

assign n_ce1 = grp_exec_pipeline_Pipeline_VITIS_LOOP_27_1_fu_267_n_ce1;

endmodule //simulatedAnnealingTop_exec_pipeline
